abahachuk/ptushki-backend

.github/PULL_REQUEST_TEMPLATE.md
As is) Please, leave feedback on it
=> EPMCUXDA-6483: add PR template

config/default.ts, src/consts/controllers.ts, src/controllers/index.ts, src/controllers/observation-controller.ts, src/controllers/users-controller.ts, src/routes.ts
`Add Observation controller.`
`run app, send requests to /observations`
- [EPMCUXDA-6602](https://jira.epam.com/jira/browse/EPMCUXDA-6602)
=> EPMCUXDA-6602: Observation Controller

src/controllers/index.ts, src/controllers/rings-by-controller.ts, src/routes.ts
Adds controller for Belarusian rings
- [EPMCUXDA-6483](https://jira.epam.com/jira/browse/EPMCUXDA-6483)
=> EPMCUXDA-6483: Add controller for Rings

.prettierrc.js, package-lock.json, package.json, src/db/index.ts, src/db/prepare-db-config.ts, src/db/run-fixtures.ts, src/entities/user-entity.ts, src/fixtures/User.yml, src/fixtures/UserProcessor.ts, src/utils/async-queue.ts
Add initial setup for fixtures uploading and adds first and easiest fixture for `Users`
Run `npm run fixtures`
- [EPMCUXDA-6598](https://jira.epam.com/jira/browse/EPMCUXDA-6598)
=>  EPMCUXDA-6598 Add user fixtures

src/controllers/abstract-controller.ts, src/controllers/observation-controller.ts, src/controllers/rings-by-controller.ts, src/controllers/users-controller.ts
Moves `checkId` to parent class & adds entity setter to make it work
--------
Also, I checked RingsBy controller and found some issues that I had fixed
- [EPMCUXDA-6620](https://jira.epam.com/jira/browse/EPMCUXDA-6620)
=> EPMCUXDA-6620: move params checking to abstract controller

src/controllers/auth-controller.ts, src/services/auth-service.ts
checkUserRole is a mIddleware that allows to check user's role according to security levels. Works only after passport-jwt middleware (it gets user from token before role checking).
`List of steps to reproduce, corroborate or tests to run. Write this section clear enough so that external users can also follow it and test the fix or feature.`
- [EPMCUXDA-6611](https://jira.epam.com/jira/browse/EPMCUXDA-6611)
`Just remove section if it isn't related to anything`
- https://github.com/abahachuk/ptushki-backend/pull/XXX
- https://github.com/abahachuk/ptushki-frontend/pull/XXX
- https://github.com/abahachuk/ptushki-mobile/pull/XXX
`Screenshots of the feature or bug if available.`
`If exists, to another …
=> EPMCUXDA-6611: implement role checking POC

src/controllers/auth-controller.ts
changePassword method allows to change user's password
`List of steps to reproduce, corroborate or tests to run. Write this section clear enough so that external users can also follow it and test the fix or feature.`
- [EPMCUXDA-6668](https://jira.epam.com/jira/browse/EPMCUXDA-6668)
`Just remove section if it isn't related to anything`
- https://github.com/abahachuk/ptushki-backend/pull/XXX
- https://github.com/abahachuk/ptushki-frontend/pull/XXX
- https://github.com/abahachuk/ptushki-mobile/pull/XXX
`Screenshots of the feature or bug if available.`
`If exists, to another developer or reviewer.`
=> Epmcuxda 6668 password change

package-lock.json, src/entities/basa-ring-entity.ts, src/entities/observation-entity.ts, src/entities/ring-entity.ts
Added automatic populations in tables using eager
Try to make requests to api
- [EPMCUXDA-6754](https://jira.epam.com/jira/browse/EPMCUXDA-6754)
=> EPMCUXDA-6754: Added automatic populations in tables using eager

src/db/run-fixtures.ts, src/utils/clean-write-line.ts
Adds counter of fixtures loading progress
=> EPMCUXDA-6483 add fixturesmeter

config/default.ts, src/controllers/observation-controller.ts, src/entities/observation-entity.ts, src/routes.ts, src/services/observation-service.ts
Bunch of endpoints for observation list
- [EPMCUXDA-6640](https://jira.epam.com/jira/browse/EPMCUXDA-6640)
=> Epmcuxda 6640. Observation List POC

Dockerfile, build.sh, package-lock.json
Created Dockerfile and build script for deployment proccess
You can make build docker image and push it to docker registry, then pull docker in vm.
- [EPMCUXDA-6836](https://jira.epam.com/jira/browse/EPMCUXDA-6836)
=> EPMCUXDA-6836: Create Dockerfile and build script for deployment

.circleci/config.yml, package-lock.json, src/db/access-parser/run.ts
Created config for circleci
- [EPMCUXDA-6837](https://jira.epam.com/jira/browse/EPMCUXDA-6837)
=> EPMCUXDA-6837: Created circleci config

src/services/observation-service.ts
`Change filters population logic`
- [EPMCUXDA-6879](https://jira.epam.com/jira/browse/EPMCUXDA-6879)
- https://github.com/abahachuk/ptushki-frontend/pull/26
=> EPMCUXDA-6879 (Observations List: Web App development - add filters) - reduce filter data

config/default.ts, src/controllers/observation-controller.ts, src/services/observation-service.ts
Dumb role checking in getObservations was applied. And I added clearing sensitive user's data in getObservations response. 
Also I want to add 'lang' query param handling to map all data with desc_eng, desc_rus, desc_byn with one 'desc' param.
=> Epmcuxda 6640. User role checking and 'lang' param

src/controllers/auth-controller.spec.ts, src/controllers/auth-controller.ts, src/entities/user-entity.ts, src/services/auth-service.ts
sanitizing user's sensitive  data
- [EPMCUXDA-6939](https://jira.epam.com/jira/browse/EPMCUXDA-6939)
=> EPMCUXDA-6939: Implement sanitizing user's sensitive  data

src/entities/observation-entity.ts
Adds an array of photos to the model
- [EPMCUXDA-6953](https://jira.epam.com/jira/browse/EPMCUXDA-6953)
=> EPMCUXDA-6953 add photos field

package-lock.json, src/fixtures/ObservationProcessor.ts
Fixing types issue in order to app started on server
Start application on production
=> Fixing types issue in order to app started on server

src/app.ts, src/controllers/initial-data-controller.ts, src/index.ts, src/routes.ts
Makes routes initilization async and adds heating up for initial-data controller
- [EPMCUXDA-6851](https://jira.epam.com/jira/browse/EPMCUXDA-6851)
=> EPMCUXDA-6851 Initialize initial-data endpoint more gently -- by heating up

src/entities/euring-codes/place-code-entity.ts, src/fixtures/PlaceCode.yml, src/fixtures/PlaceCodeProcessor.ts
I applied descriptions for place-code-entity. Also fixtures was updated. Right now I added only Belarus regions.
=> improve placeCode entity with description

src/controllers/observation-controller.ts, src/entities/observation-entity.ts, src/fixtures/Observation.yml, swagger.json
Add endpoint for verification status updating
https://jira.epam.com/jira/browse/EPMCUXDA-6965
=> EPMCUXDA-6965: add endpoint for verification status updating

src/fixtures/User.yml
add admin firsName and lastName just for demo
=> Improve user fixture

src/entities/observation-entity.ts
Add default null for ringMentioned
=> hotfix_ring_mentioned: add default null for ringMentioned

src/controllers/observation-controller.ts, src/services/export/XLSExporterForObservations.ts, src/services/observation-service.ts
introduce 'lang' param for getting observations.
e.g.  /observations?lang=desc_rus
=> EPMCUXDA-6640: introduce 'lang' param

src/entities/observation-entity.ts, src/services/export/AbstractExporter.ts, src/services/export/EURINGExporterForObservations.ts, src/services/export/XLSExporterForObservations.ts, src/services/import/AbstractImporter.ts, src/services/import/EURINGImporterForObservations.ts, src/utils/coords-parser.ts, src/utils/custom-parsers.ts, src/utils/date-parser.ts, src/validation/validation-messages.ts
Export/import EURING codes added in API
Run in dev mode, then make POST queries in localhost:3001/observations/export/euring, you can put rowIds: string[]
- [EPMCUXDA-6950](https://jira.epam.com/jira/browse/EPMCUXDA-6950)
=> Epmcuxda 6950: Export/import EURING

src/app.ts
Update paths to run app in prod env
- [EPMCUXDA-6949](https://jira.epam.com/jira/browse/EPMCUXDA-6949)
=> EPMCUXDA-6949 - fix: update paths to run app in prod env

config/default.ts, package-lock.json, src/controllers/observation-controller.ts, src/controllers/rings-by-controller.ts, src/entities/common-interfaces.ts, src/entities/ring-entity.ts, src/fixtures/Condition.yml, src/services/export/XLSExporterForObservations.ts, src/services/observation-service.ts, src/services/page-service.ts
Search page params for Rings were introduced.
- [EPMCUXDA-7057](https://jira.epam.com/jira/browse/EPMCUXDA-7057)
=> EPMCUXDA-7057: Rings pagination

src/entities/euring-codes/place-code-entity.ts, src/entities/observation-entity.ts, src/entities/ring-entity.ts, src/fixtures/PlaceCode.yml
Extends valid values for `PlaceCode` -- currently codes like `BY--` are unvalid
=> update validator used for place code

src/controllers/users-controller.ts, src/entities/user-entity.ts, src/fixtures/User.yml
Adds `phone` property to `User`
Also **fixes 2 bugs**:
- accidentially instead new password was saved old again
- check for required params for new email was wrong it was expecting that both password and email aren't provided
And makes **small impovement**:
- checks that new password differ from old one
Please test all 3 user related endpoints
1. PUT `user/:id`
3. PUT `user/:id/update-email`
4. PUT `user/:id/update-password`
#78 previous PR which had introduced these bugs
=> fix: User updating (email, password, add phone)

src/controllers/observation-controller.ts, src/entities/observation-entity.ts
Updates contract for creating observation: 
- removes `ring`
- removes `distance`
- removes `direction`
- removes `placeCode`
Also makes some fields optional for validation:
- `offlineFinder`
- `ringingScheme`
- `primaryIdentificationMethod`
- `verificationOfTheMetalRing`
- `metalRingInformation`
- `otherMarksInformation`
- `euringCodeIdentifier`
- `broodSize`
- `placeCode`
=> review Observation contracts
